# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ScreenCloudMSFFramework' do
	pod "ConnectSDK"
end

target 'ScreenCloudMSFFrameworkTests' do
	pod "ConnectSDK"
end

